name: Run All Commodity and Energy Indicators Scripts in Parallel

on:
  schedule:
    - cron: "0 0 * * *"  # Every hour
  workflow_dispatch:

env:
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

jobs:
  run-crude-oil-prices:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 yfinance
      - name: Run Crude Oil Prices Script
        run: python "code/daily/fetch_crude_oil_prices.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/daily/fetch_crude_oil_prices.py"
        continue-on-error: true

  run-natural-gas-prices:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 yfinance
      - name: Run Natural Gas Prices Script
        run: python "code/daily/fetch_natural_gas_prices.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/daily/fetch_natural_gas_prices.py"
        continue-on-error: true

  run-coal-prices:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 yfinance
      - name: Run Coal Prices Script
        run: python "code/monthly/fetch_coal_prices.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/monthly/fetch_coal_prices.py"
        continue-on-error: true

  run-electricity-prices:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 yfinance
      - name: Run Electricity Prices Script
        run: python "code/monthly/fetch_electricity_prices.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/monthly/fetch_electricity_prices.py"
        continue-on-error: true

  run-commodity-price-index:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 yfinance
      - name: Run Commodity Price Index Script
        run: python "code/monthly/fetch_commodity_price_index.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/monthly/fetch_commodity_price_index.py"
        continue-on-error: true

  run-agricultural-prices:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 yfinance
      - name: Run Agricultural Prices Script
        run: python "code/monthly/fetch_agricultural_prices.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/monthly/fetch_agricultural_prices.py"
        continue-on-error: true

  run-metal-prices:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 yfinance
      - name: Run Metal Prices Script
        run: python "code/monthly/fetch_metal_prices.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/monthly/fetch_metal_prices.py"
        continue-on-error: true

  run-gold-prices:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 yfinance
      - name: Run Gold Prices Script
        run: python "code/daily/fetch_gold_prices.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/daily/fetch_gold_prices.py"
        continue-on-error: true

  run-strategic-reserves:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 yfinance
      - name: Run Strategic Reserves Script
        run: python "code/weekly/fetch_strategic_reserves.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/weekly/fetch_strategic_reserves.py"
        continue-on-error: true

  run-energy-consumption:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 yfinance
      - name: Run Energy Consumption Script
        run: python "code/yearly/fetch_energy_consumption.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/yearly/fetch_energy_consumption.py"
        continue-on-error: true
