name: Crypto Scripts Tests

on:
  push:
    paths:
      - 'code/daily/AlphaVantage DXY.py'
      - 'code/daily/Alternative.me Fear and Greed Index.py'
      - 'code/daily/Binance Futures Stats.py'
      - 'code/daily/Blockchair Stats.py'
      - 'code/daily/DefiLlama Stats.py'
      - 'code/daily/Etherscan Stats.py'
      - 'code/daily/Mempool Stats.py'
      - 'code/daily/OpenSea NFT Stats.py'
      - 'code/daily/OpenSea NFT Transfers.py'
      - 'tests/**'
  pull_request:
    paths:
      - 'code/daily/AlphaVantage DXY.py'
      - 'code/daily/Alternative.me Fear and Greed Index.py'
      - 'code/daily/Binance Futures Stats.py'
      - 'code/daily/Blockchair Stats.py'
      - 'code/daily/DefiLlama Stats.py'
      - 'code/daily/Etherscan Stats.py'
      - 'code/daily/Mempool Stats.py'
      - 'code/daily/OpenSea NFT Stats.py'
      - 'code/daily/OpenSea NFT Transfers.py'
      - 'tests/**'

jobs:
  test-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest -q
