name: Run All Labor Market and Demographics Scripts in Parallel

on:
  schedule:
    - cron: "0 0 * * *"  # Every hour
  workflow_dispatch:

env:
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
  BLS_API_KEY: ${{ secrets.BLS_API_KEY }}

jobs:
  run-labor-force-participation:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Labor Force Participation Script
        run: python "code/monthly/fetch_labor_force_participation.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/monthly/fetch_labor_force_participation.py"
        continue-on-error: true

  run-wage-growth-rates:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Wage Growth Rates Script
        run: python "code/monthly/fetch_wage_growth_rates.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/monthly/fetch_wage_growth_rates.py"
        continue-on-error: true

  run-job-vacancy-rates:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Job Vacancy Rates Script
        run: python "code/monthly/fetch_job_vacancy_rates.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/monthly/fetch_job_vacancy_rates.py"
        continue-on-error: true

  run-employment-population-ratio:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Employment-to-Population Ratio Script
        run: python "code/monthly/fetch_employment_population_ratio.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/monthly/fetch_employment_population_ratio.py"
        continue-on-error: true

  run-youth-unemployment-rate:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Youth Unemployment Rate Script
        run: python "code/monthly/fetch_youth_unemployment_rate.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/monthly/fetch_youth_unemployment_rate.py"
        continue-on-error: true

  run-aging-population-metrics:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Aging Population Metrics Script
        run: python "code/yearly/fetch_aging_population_metrics.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/yearly/fetch_aging_population_metrics.py"
        continue-on-error: true

  run-migration-rates:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Migration Rates Script
        run: python "code/yearly/fetch_migration_rates.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/yearly/fetch_migration_rates.py"
        continue-on-error: true

  run-education-attainment-levels:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Education Attainment Levels Script
        run: python "code/yearly/fetch_education_attainment_levels.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/yearly/fetch_education_attainment_levels.py"
        continue-on-error: true

  run-labor-productivity:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Labor Productivity Script
        run: python "code/quarterly/fetch_labor_productivity.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/quarterly/fetch_labor_productivity.py"
        continue-on-error: true

  run-unionization-rates:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Unionization Rates Script
        run: python "code/yearly/fetch_unionization_rates.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/yearly/fetch_unionization_rates.py"
        continue-on-error: true
