name: Run All Economic Indicator Scripts

on:
  schedule:
    - cron: "0 0 * * *"  # Every hour
  workflow_dispatch:

env:
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

jobs:
  run-all-indicators:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader

      - name: Run All Scripts
        run: python run_all_scripts.py
