name: Run All Economic Indicator Scripts in Parallel

on:
  schedule:
    - cron: "0 0 * * *"  # Every hour
  workflow_dispatch:

env:
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

jobs:
  run-gross-domestic-product:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Gross Domestic Product Script
        run: python "code/Macro-Level economic indicators/Gross Domestic Product.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Gross Domestic Product.py"
        continue-on-error: true

  run-gdp-growth-rate:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run GDP Growth Rate Script
        run: python "code/Macro-Level economic indicators/GDP Growth Rate.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/GDP Growth Rate.py"
        continue-on-error: true

  run-inflation-rate-cpi:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Inflation Rate (CPI) Script
        run: python "code/Macro-Level economic indicators/Inflation Rate (CPI).py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Inflation Rate (CPI).py"
        continue-on-error: true

  run-unemployment-rate:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Unemployment Rate Script
        run: python "code/Macro-Level economic indicators/Unemployment Rate.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Unemployment Rate.py"
        continue-on-error: true

  run-interest-rates:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Interest Rates (Federal Funds Rate) Script
        run: python "code/Macro-Level economic indicators/Interest Rates (Federal Funds Rate).py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Interest Rates (Federal Funds Rate).py"
        continue-on-error: true

  run-money-supply-m2:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Money Supply (M2) Script
        run: python "code/Macro-Level economic indicators/Money Supply (M2).py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Money Supply (M2).py"
        continue-on-error: true

  run-consumer-confidence:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Consumer Confidence Index Script
        run: python "code/Macro-Level economic indicators/Consumer Confidence Index.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Consumer Confidence Index.py"
        continue-on-error: true

  run-business-confidence:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Business Confidence Index Script
        run: python "code/Macro-Level economic indicators/Business Confidence Index.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Business Confidence Index.py"
        continue-on-error: true

  run-retail-sales:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Retail Sales Script
        run: python "code/Macro-Level economic indicators/Retail Sales.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Retail Sales.py"
        continue-on-error: true

  run-industrial-production:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-data-reader
      - name: Run Industrial Production Script
        run: python "code/Macro-Level economic indicators/Industrial Production.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Industrial Production.py"
        continue-on-error: true

  run-capacity-utilization:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Capacity Utilization Script
        run: python "code/Macro-Level economic indicators/Capacity Utilization.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Capacity Utilization.py"
        continue-on-error: true

  run-pmi:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Purchasing Managers' Index (PMI) Script
        run: python "code/Macro-Level economic indicators/Purchasing Managers' Index (PMI).py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Purchasing Managers' Index (PMI).py"
        continue-on-error: true

  run-housing-starts:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Housing Starts Script
        run: python "code/Macro-Level economic indicators/Housing Starts.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Housing Starts.py"
        continue-on-error: true

  run-building-permits:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Building Permits Script
        run: python "code/Macro-Level economic indicators/Building Permits.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Building Permits.py"
        continue-on-error: true

  run-trade-balance:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Trade Balance Script
        run: python "code/Macro-Level economic indicators/Trade Balance.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Trade Balance.py"
        continue-on-error: true

  run-current-account-balance:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-data-reader
      - name: Run Current Account Balance (OECD) Script
        run: python "code/Macro-Level economic indicators/Current Account Balance (OECD).py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Current Account Balance (OECD).py"
        continue-on-error: true

  run-fdi:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Foreign Direct Investment (FDI) (UNCTAD) Script
        run: python "code/Macro-Level economic indicators/Foreign Direct Investment (FDI) (UNCTAD).py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Foreign Direct Investment (FDI) (UNCTAD).py"
        continue-on-error: true

  run-government-budget-balance:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Government Budget Balance (OECD) Script
        run: python "code/Macro-Level economic indicators/Government Budget Balance (OECD).py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Government Budget Balance (OECD).py"
        continue-on-error: true

  run-public-debt-levels:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Public Debt Levels (IMF) Script
        run: python "code/Macro-Level economic indicators/Public Debt Levels (IMF).py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Public Debt Levels (IMF).py"
        continue-on-error: true

  run-exchange-rates:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Exchange Rates (Investing.com) Script
        run: python "code/Macro-Level economic indicators/Exchange Rates (Investing.com).py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Macro-Level economic indicators/Exchange Rates (Investing.com).py"
        continue-on-error: true
