name: Quarterly Jobs

on:
  schedule:
    - cron: "0 0 1 */3 *"
  workflow_dispatch:

jobs:
  run-quarterly-scripts:
    name: ${{ matrix.script }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        script:
          - "code/quarterly/Current Account Balance (OECD).py"
          - "code/quarterly/GDP Growth Rate.py"
          - "code/quarterly/Government Budget Balance (OECD).py"
          - "code/quarterly/Gross Domestic Product.py"
          - "code/quarterly/data_upload_utils.py"
          - "code/quarterly/fetch_corporate_debt_levels.py"
          - "code/quarterly/fetch_household_debt_levels.py"
          - "code/quarterly/fetch_labor_productivity.py"
          - "code/quarterly/fetch_mortgage_default_rates.py"
    env:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run ${{ matrix.script }}
        run: python "${{ matrix.script }}"
