name: Quarterly Jobs

on:
  schedule:
    - cron: "0 0 1 */3 *"
  workflow_dispatch:

jobs:
  run-quarterly-scripts:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run quarterly scripts
        run: |
          shopt -s nullglob
          for script in code/quarterly/*.py; do
            echo "Running $script"
            python "$script" || echo "Failed $script"
          done
