name: Run OHLC Data Fetcher

on:
  schedule:
    # Runs every day at midnight UTC (adjust as needed)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows for manual trigger via GitHub UI
  
jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install required dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nbconvert  # Install nbconvert to run Jupyter notebooks

    # Step 4: Run the Jupyter notebook using nbconvert
    - name: Run the Jupyter notebook
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        jupyter nbconvert --to notebook --execute PricesScript.ipynb --output result.ipynb

    # Optional: Step 5: Cleanup (e.g., remove any temporary files)
    - name: Cleanup
      run: |
        rm -rf __pycache__ .pytest_cache
