name: Run All Scripts

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:

jobs:
  run-ohlc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run OHLC Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/PricesScript.py"

  run-volume:
    needs: run-ohlc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run VolumeTraded Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/VolumeTraded.py"

  run-trading-range:
    needs: run-volume
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Trading Range Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/24h Volatility & Trading Range.py"

  run-trending-search:
    needs: run-trading-range
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Google Trending Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/GoogleTrending.py"

  run-bitcoin-halving:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Bitcoin Halving Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/BitcoinHalving.py"

  run-consumer-confidence:
    needs: run-bitcoin-halving
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Consumer Confidence Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/ConsumerConfidence.py"

  run-currency-exchange:
    needs: run-consumer-confidence
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Currency Exchange Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/CurrencyExchange.py"

  run-gdp-data:
    needs: run-currency-exchange
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run GDP Data Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/GDPData.py"

  run-global-gdp:
    needs: run-gdp-data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Global GDP Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/GlobalGDP.py"

  run-gold-daily-price:
    needs: run-global-gdp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Gold Daily Price Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/GoldDailyPrice.py"

  run-housing-permit:
    needs: run-gold-daily-price
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Housing Permit Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/HousingPermit.py"

  run-inflation-data:
    needs: run-housing-permit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Inflation Data Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/InflationData.py"

  run-interest-rate:
    needs: run-inflation-data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Interest Rate Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/InterestRate.py"

  run-labor-force-participation:
    needs: run-interest-rate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Labor Force Participation Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/LaborForceParticipation.py"

  run-m2-data:
    needs: run-labor-force-participation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run M2 Data Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/M2Data.py"

  run-market-cap:
    needs: run-m2-data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Market Cap Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/MarketCap.py"

  run-qqq-data:
    needs: run-market-cap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run QQQ Data Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/QQQData.py"

  run-spy-data:
    needs: run-qqq-data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run SPY Data Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/SPYData.py"

  run-us-dollar-index:
    needs: run-spy-data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run USDollar Index Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/USDollarIndex.py"

  run-unemployment-data:
    needs: run-us-dollar-index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Unemployment Data Notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python "code/UnemploymentData.py"
