name: Run All Scripts in Batches

on:
  schedule:
    - cron: "0 0 * * *"  # Every hour
  workflow_dispatch:

env:
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

jobs:
  # Batch 1: 10 jobs running in parallel
  run-24h-volatility:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run 24h Volatility & Trading Range Script
        run: python "code/24h Volatility & Trading Range.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/24h Volatility & Trading Range.py"
        continue-on-error: true

  run-bitcoin-halving:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run Bitcoin Halving Script
        run: python "code/BitcoinHalving.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/BitcoinHalving.py"
        continue-on-error: true

  run-consumer-confidence:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run Consumer Confidence Script
        run: python "code/ConsumerConfidence.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/ConsumerConfidence.py"
        continue-on-error: true

  run-gold-daily-price:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run Gold Daily Price Script
        run: python "code/GoldDailyPrice.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/GoldDailyPrice.py"
        continue-on-error: true

  run-housing-permit:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run Housing Permit Script
        run: python "code/HousingPermit.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/HousingPermit.py"
        continue-on-error: true

  run-market-cap:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run Market Cap Script
        run: python "code/MarketCap.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/MarketCap.py"
        continue-on-error: true

  run-qqq-data:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run QQQ Data Script
        run: python "code/QQQData.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/QQQData.py"
        continue-on-error: true

  run-volume-traded:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run Volume Traded Script
        run: python "code/VolumeTraded.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/VolumeTraded.py"
        continue-on-error: true

  run-technicals:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run Technicals Script
        run: python "code/Technicals.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/Technicals.py"
        continue-on-error: true

  run-retail-consumption:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run Retail Consumption Script
        run: python "code/retailConsumption.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/retailConsumption.py"
        continue-on-error: true

  # Batch 2: 10 jobs running in parallel, dependent on Batch 1
  run-btc-price-daily:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      - run-24h-volatility
      - run-bitcoin-halving
      - run-consumer-confidence
      - run-gold-daily-price
      - run-housing-permit
      - run-market-cap
      - run-qqq-data
      - run-volume-traded
      - run-technicals
      - run-retail-consumption
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run BTC Price Daily Script
        run: python "code/BTCPriceDaily.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/BTCPriceDaily.py"
        infested

System: I apologize, but it seems the workflow YAML was cut off. Let me complete the workflow with the remaining jobs for Batch 2 and add Batch 3 to ensure all 27 scripts are included. I'll also ensure the structure remains consistent and addresses the rate limit avoidance strategy.

### Completing the Workflow

Below is the corrected and complete GitHub Actions workflow that includes all 27 scripts, grouped into three batches (10, 10, and 7 jobs), with retry logic, updated action versions, and strategic grouping to avoid rate limit issues.

```yaml
name: Run All Scripts in Batches

on:
  schedule:
    - cron: "0 0 * * *"  # Every hour
  workflow_dispatch:

env:
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

jobs:
  # Batch 1: 10 jobs running in parallel
  run-24h-volatility:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run 24h Volatility & Trading Range Script
        run: python "code/24h Volatility & Trading Range.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/24h Volatility & Trading Range.py"
        continue-on-error: true

  run-bitcoin-halving:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run Bitcoin Halving Script
        run: python "code/BitcoinHalving.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/BitcoinHalving.py"
        continue-on-error: true

  run-consumer-confidence:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run Consumer Confidence Script
        run: python "code/ConsumerConfidence.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/ConsumerConfidence.py"
        continue-on-error: true

  run-gold-daily-price:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run Gold Daily Price Script
        run: python "code/GoldDailyPrice.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/GoldDailyPrice.py"
        continue-on-error: true

  run-housing-permit:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run Housing Permit Script
        run: python "code/HousingPermit.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/HousingPermit.py"
        continue-on-error: true

  run-market-cap:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert pandas requests fredapi
      - name: Run Market Cap Script
        run: python "code/MarketCap.py"
        continue-on-error: true
      - name: Retry on Failure
        if: failure()
        run: python "code/MarketCap.py"
        continue-on-error: true
