name: Run OHLC Data Fetcher

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger via GitHub UI

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert  # Needed to run Jupyter notebooks

      - name: Run OHLC notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          jupyter nbconvert --to notebook --execute PricesScript.ipynb --output ohlc_output.ipynb

      - name: Run Volume notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          jupyter nbconvert --to notebook --execute VolumeTraded.ipynb --output volume_output.ipynb
          
      - name: Run Trading Range notebook
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          jupyter nbconvert --to notebook --execute "24h Volatility & Trading Range.ipynb" --output volume_output.ipynb

      - name: Cleanup
        run: |
          rm -rf __pycache__ .pytest_cache
