name: Run All Scripts Sequentially

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:

env:
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

jobs:
  run-ohlc:
    runs-on: ubuntu-latest
    continue-on-error: true  # Continue even if this job fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run OHLC Notebook
        run: python "code/PricesScript.py"

  run-volume:
    runs-on: ubuntu-latest
    needs: run-ohlc
    continue-on-error: true  # Continue even if this job fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run VolumeTraded Notebook
        run: python "code/VolumeTraded.py"

  run-trading-range:
    runs-on: ubuntu-latest
    needs: run-volume
    continue-on-error: true  # Continue even if this job fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Trading Range Notebook
        run: python "code/24h Volatility & Trading Range.py"

  run-trending-search:
    runs-on: ubuntu-latest
    needs: run-trading-range
    continue-on-error: true  # Continue even if this job fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Google Trending Notebook
        run: python "code/GoogleTrending.py"

  run-bitcoin-halving:
    runs-on: ubuntu-latest
    needs: run-trending-search
    continue-on-error: true  # Continue even if this job fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Bitcoin Halving Notebook
        run: python "code/BitcoinHalving.py"

  run-gold-price:
    runs-on: ubuntu-latest
    needs: run-bitcoin-halving
    continue-on-error: true  # Continue even if this job fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Gold Price Notebook
        run: python "code/GoldDailyPrice.py"

  run-housing-permit:
    runs-on: ubuntu-latest
    needs: run-gold-price
    continue-on-error: true  # Continue even if this job fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Housing Permit Notebook
        run: python "code/HousingPermit.py"

  run-m2-data:
    runs-on: ubuntu-latest
    needs: run-housing-permit
    continue-on-error: true  # Continue even if this job fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run M2 Data Notebook
        run: python "code/M2Data.py"

  run-qqq-data:
    runs-on: ubuntu-latest
    needs: run-m2-data
    continue-on-error: true  # Continue even if this job fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run QQQ Data Notebook
        run: python "code/QQQData.py"

  run-spy-data:
    runs-on: ubuntu-latest
    needs: run-qqq-data
    continue-on-error: true  # Continue even if this job fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run SPY Data Notebook
        run: python "code/SPYData.py"

  run-usd-index:
    runs-on: ubuntu-latest
    needs: run-spy-data
    continue-on-error: true  # Continue even if this job fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run USD Index Notebook
        run: python "code/USDollarIndex.py"

  run-unemployment:
    runs-on: ubuntu-latest
    needs: run-usd-index
    continue-on-error: true  # Continue even if this job fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Unemployment Data Notebook
        run: python "code/UnemploymentData.py"

  run-retail-consumption:
    runs-on: ubuntu-latest
    needs: run-unemployment
    continue-on-error: true  # Continue even if this job fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Retail Consumption Notebook
        run: python "code/retailConsumption.py"
