name: Run All Scripts

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:

env:
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

jobs:
  run-ohlc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run OHLC Notebook
        run: python "code/PricesScript.py"

  run-volume:
    runs-on: ubuntu-latest
    needs: run-ohlc
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run VolumeTraded Notebook
        run: python "code/VolumeTraded.py"

  run-trading-range:
    runs-on: ubuntu-latest
    needs: run-ohlc
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Trading Range Notebook
        run: python "code/24h Volatility & Trading Range.py"

  run-trending-search:
    runs-on: ubuntu-latest
    needs: run-ohlc
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Google Trending Notebook
        run: python "code/GoogleTrending.py"

  run-bitcoin-halving:
    runs-on: ubuntu-latest
    needs: run-ohlc
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Bitcoin Halving Notebook
        run: python "code/BitcoinHalving.py"

  run-consumer-confidence:
    runs-on: ubuntu-latest
    needs: run-ohlc
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Consumer Confidence Notebook
        run: python "code/ConsumerConfidence.py"

  run-currency-exchange:
    runs-on: ubuntu-latest
    needs: run-ohlc
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Currency Exchange Notebook
        run: python "code/CurrencyExchange.py"

  run-gdp-data:
    runs-on: ubuntu-latest
    needs: run-ohlc
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run GDP Data Notebook
        run: python "code/GDPData.py"

  run-global-gdp:
    runs-on: ubuntu-latest
    needs: run-gdp-data
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Global GDP Notebook
        run: python "code/GlobalGDP.py"

  run-gold-daily-price:
    runs-on: ubuntu-latest
    needs: run-global-gdp
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Gold Daily Price Notebook
        run: python "code/GoldDailyPrice.py"

  run-housing-permit:
    runs-on: ubuntu-latest
    needs: run-gold-daily-price
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Housing Permit Notebook
        run: python "code/HousingPermit.py"

  run-inflation-data:
    runs-on: ubuntu-latest
    needs: run-housing-permit
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Inflation Data Notebook
        run: python "code/InflationData.py"

  run-interest-rate:
    runs-on: ubuntu-latest
    needs: run-inflation-data
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Interest Rate Notebook
        run: python "code/InterestRate.py"

  run-labor-force-participation:
    runs-on: ubuntu-latest
    needs: run-interest-rate
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Labor Force Participation Notebook
        run: python "code/LaborForceParticipation.py"

  run-m2-data:
    runs-on: ubuntu-latest
    needs: run-labor-force-participation
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run M2 Data Notebook
        run: python "code/M2Data.py"

  run-market-cap:
    runs-on: ubuntu-latest
    needs: run-m2-data
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Market Cap Notebook
        run: python "code/MarketCap.py"
