name: Weekly Jobs

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

env:
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script:
          - 'code/weekly/bitcoin_close_1wk.py'
          - 'code/weekly/fetch_money_market_fund_flows.py'
          - 'code/weekly/fetch_strategic_reserves.py'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader
      - name: Run Script
        run: python ${{ matrix.script }}
      - name: Retry on Failure
        if: failure()
        run: python ${{ matrix.script }}
