name: Weekly Jobs

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  run-bitcoin-weekly:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader

      - name: Run weekly BTC data
        run: python "code/weekly/bitcoin_close_1wk.py"
        continue-on-error: true

      - name: Retry on Failure
        if: failure()
        run: python "code/weekly/bitcoin_close_1wk.py"
        continue-on-error: true

  run-money-market-weekly:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader

      - name: Run money market weekly
        run: python "code/weekly/fetch_money_market_fund_flows.py"
        continue-on-error: true

      - name: Retry on Failure
        if: failure()
        run: python "code/weekly/fetch_money_market_fund_flows.py"
        continue-on-error: true

  run-strategic-reserve-weekly:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install fredapi pandas openpyxl requests beautifulsoup4 pandas-datareader

      - name: Run strategic reserve
        run: python "code/weekly/fetch_strategic_reserves.py"
        continue-on-error: true

      - name: Retry on Failure
        if: failure()
        run: python "code/weekly/fetch_strategic_reserves.py"
        continue-on-error: true
