name: Weekly Jobs

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  run-weekly-scripts:
    name: ${{ matrix.script }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        script:
          - "code/weekly/bitcoin_close_1wk.py"
          - "code/weekly/data_upload_utils.py"
          - "code/weekly/fetch_money_market_fund_flows.py"
          - "code/weekly/fetch_strategic_reserves.py"
          - "code/weekly/5-Year TIPS Yield.py"
          - "code/weekly/10-Year TIPS Yield.py"
          - "code/weekly/20-Year TIPS Yield.py"
          - "code/weekly/30-Year TIPS Yield.py"
    env:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run ${{ matrix.script }}
        run: python "${{ matrix.script }}"
